################################################################################
#
# @author      : Thomas Maxson
# @package     : Custom Fans
# @description :
#
################################################################################

fan:
  - platform: template
    fans:
      custom_garage_fan:
        unique_id: "custom-garage-fan-001"
        friendly_name: "Garage Fan"
        turn_on:
          action: light.turn_on
          target:
            entity_id: light.garage_fan
        turn_off:
          action: light.turn_off
          target:
            entity_id: light.garage_fan
        value_template: "{{ is_state( 'light.garage_fan', 'on' ) }}"

      bedroom_1_ceiling_for_alexa:
        unique_id: "fan-bedroom-ceiling-for-alexa-001"
        friendly_name: "Fan, Bedroom 1 (for Alexa)"
        value_template: "{{ states( 'fan.bedroom_1_ceiling' ) }}"
        turn_on:
          - action: fan.turn_on
            target:
              entity_id: fan.bedroom_1_ceiling
        turn_off:
          - action: fan.turn_off
            target:
              entity_id: fan.bedroom_1_ceiling
        percentage_template: >
          {{ state_attr( 'fan.bedroom_1_ceiling', 'percentage' ) }}
        speed_count: 3
        set_percentage:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_1_ceiling
            data:
              percentage: "{{ percentage }}"
        preset_modes:
          - "off"
          - "low"
          - "medium"
          - "high"
        preset_mode_template: >
          {% if is_state( 'fan.bedroom_1_ceiling', 'on' ) %}
            {% if state_attr( 'fan.bedroom_1_ceiling', 'percentage' ) >= 100  %}
              high
            {% elif state_attr( 'fan.bedroom_1_ceiling', 'percentage' ) >= 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_1_ceiling
            data:
              percentage: >-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}

      bedroom_2_ceiling_for_alexa:
        unique_id: "fan-bedroom-ceiling-for-alexa-002"
        friendly_name: "Fan, Bedroom 2 (for Alexa)"
        value_template: "{{ states( 'fan.bedroom_2_ceiling' ) }}"
        turn_on:
          - action: fan.turn_on
            target:
              entity_id: fan.bedroom_2_ceiling
        turn_off:
          - action: fan.turn_off
            target:
              entity_id: fan.bedroom_2_ceiling
        percentage_template: >
          {{ state_attr( 'fan.bedroom_2_ceiling', 'percentage' ) }}
        speed_count: 3
        set_percentage:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_2_ceiling
            data:
              percentage: "{{ percentage }}"
        preset_modes:
          - "off"
          - "low"
          - "medium"
          - "high"
        preset_mode_template: >
          {% if is_state( 'fan.bedroom_2_ceiling', 'on' ) %}
            {% if state_attr( 'fan.bedroom_2_ceiling', 'percentage' ) >= 100  %}
              high
            {% elif state_attr( 'fan.bedroom_2_ceiling', 'percentage' ) >= 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_2_ceiling
            data:
              percentage: >-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}

      bedroom_3_ceiling_for_alexa:
        unique_id: "fan-bedroom-ceiling-for-alexa-003"
        friendly_name: "Fan, Bedroom 3 (for Alexa)"
        value_template: "{{ states( 'fan.bedroom_3_ceiling' ) }}"
        turn_on:
          - action: fan.turn_on
            target:
              entity_id: fan.bedroom_3_ceiling
        turn_off:
          - action: fan.turn_off
            target:
              entity_id: fan.bedroom_3_ceiling
        percentage_template: >
          {{ state_attr( 'fan.bedroom_3_ceiling', 'percentage' ) }}
        speed_count: 3
        set_percentage:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_3_ceiling
            data:
              percentage: "{{ percentage }}"
        preset_modes:
          - "off"
          - "low"
          - "medium"
          - "high"
        preset_mode_template: >
          {% if is_state( 'fan.bedroom_3_ceiling', 'on' ) %}
            {% if state_attr( 'fan.bedroom_3_ceiling', 'percentage' ) >= 100  %}
              high
            {% elif state_attr( 'fan.bedroom_3_ceiling', 'percentage' ) >= 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_3_ceiling
            data:
              percentage: >-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}

      bedroom_4_ceiling_for_alexa:
        unique_id: "fan-bedroom-ceiling-for-alexa-004"
        friendly_name: "Fan, Bedroom 4 (for Alexa)"
        value_template: "{{ states( 'fan.ceiling_bedroom_4' ) }}"
        turn_on:
          - action: fan.turn_on
            target:
              entity_id: fan.bedroom_4_ceiling
        turn_off:
          - action: fan.turn_off
            target:
              entity_id: fan.bedroom_4_ceiling
        percentage_template: >
          {{ state_attr( 'fan.bedroom_4_ceiling', 'percentage' ) }}
        speed_count: 3
        set_percentage:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_4_ceiling
            data:
              percentage: "{{ percentage }}"
        preset_modes:
          - "off"
          - "low"
          - "medium"
          - "high"
        preset_mode_template: >
          {% if is_state( 'fan.bedroom_4_ceiling', 'on' ) %}
            {% if state_attr( 'fan.bedroom_4_ceiling', 'percentage' ) == 100  %}
              high
            {% elif state_attr( 'fan.bedroom_4_ceiling', 'percentage' ) == 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - action: fan.set_percentage
            target:
              entity_id: fan.bedroom_4_ceiling
            data:
              percentage: >-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}
