################################################################################
#
# @author      : Thomas Maxson
# @package     : Group
# @description :
#
################################################################################

group:
  residents:
    name: Residents
    entities:
      - person.thomas
      - person.jessica
      - person.nicholas
