################################################################################
#
# @author      : Thomas Maxson
# @package     : Sidebar Content
# @description :
#
################################################################################

template:
  - sensor:
      - unique_id: sidebar
        state: template
        attributes:
          time: >
            {%- set hours = now().strftime( '%I' ) %}
            {%- set minutes = now().strftime( '%M' ) %}

            {{ hours }}<span class="time-colon">:</span>{{ minutes }}

          date: |
            {%- set weekday = now().strftime( '%A' ) %}
            {%- set month = now().strftime( '%B' ) %}

            {{ weekday }},<br>
            {{ month }} {{ now().day }}

          greeting: |
            {%- set hour = now().hour %}

            {%- if hour < 6 %}
              Good Night
            {%- elif hour < 12 %}
              Good Morning
            {%- elif hour < 20 %}
              Good Afternoon
            {%- else %}
              Good Evening
            {%- endif %}

          weather: |
            {%- if is_state( 'input_boolean.sidebar_display_weather_forecast', 'on' ) %}
              {%- set ignore = [ 'null', 'unknown', 'unavailable' ] -%}
              {%- set temperature = states( 'sensor.pirateweather_temperature' ) %}

              {%- if temperature not in ignore %}
                It is currently {{ temperature | round }}°

                {%- set weather_state = states('weather.pirateweather') %}
                {%- if weather_state == 'rainy' %}
                  {{ ['with expected rain', 'with expected showers'] | random }}
                  
                {%- elif weather_state == 'cloudy' %}
                  {{ ['with clouds', 'with cloudy skies'] | random }}
                  
                {%- elif weather_state == 'partlycloudy' %}
                  {{ ['with some clouds', 'with partly cloudy skies', 'with scattered clouds'] | random }}
                  
                {%- else %}
                  {%- if is_state('sun.sun', 'above_horizon') %}
                    {{ ['and sunny', 'with sunshine'] | random }}
                    
                  {%- else %}
                    {{ ['and clear', 'with clear skies'] | random }}
                    
                  {%- endif %}
                {%- endif %}
              {%- else %}
                Unable to load weather information

              {%- endif %}
            {%- endif %}

          holiday: |
            {%- if is_state( 'input_boolean.sidebar_display_holidays', 'on' ) %}
              {%- if states.calendar.holidays_in_united_states.state == 'on' %}
                Today is {{ states.calendar.holidays_in_united_states.attributes.message }}

              {%- endif %}
            {%- endif %}

          birthday: |
            {%- if is_state('input_boolean.sidebar_display_celebrations', 'on') %}
              {%- if is_state('calendar.birthdays', 'on') %}
                Today is {{ states.calendar.birthdays.attributes.message }}. {{ [
                  'Ready for another lap around the sun?',
                  'They can cry if they want to.',
                  'The confetti cannon is ready.',
                  'I hope the cake is tasty.'
                ] | random }}
              {%- endif %}
            {% endif %}

          neighborhood: |
            {%- if is_state('input_boolean.sidebar_display_neighborhood', 'on') %}
              {%- if is_state('calendar.regency_lakes', 'on') %}
                {%- set calendar = states.calendar.regency_lakes %}
                {%- set description = calendar.attributes.description %}
                {%- set message = calendar.attributes.message %}

                {{ description if description else 
                  (message ~ ' in ' ~ [
                    'your neighborhood', 
                    'Regency Lakes', 
                    'Osprey Point'
                  ] | random ~ ' today') if message else '' }}
              {%- endif %}
            {% endif %}
