################################################################################
#
# @author      : Thomas Maxson
# @package     : Secrets
# @description :
#
################################################################################

homeassistant_external_url: [REDACTED]
homeassistant_internal_url: [REDACTED]

homeassistant_latitude: [REDACTED]
homeassistant_longitude: [REDACTED]
homeassistant_elevation: [REDACTED]

recorder_db_url: mysql://homeassistant:[REDACTED]@core-mariadb/homeassistant?charset=utf8mb4

unifi_gateway: [REDACTED]
unifi_host: [REDACTED]
unifi_url: [REDACTED]
unifi_url_port: [REDACTED]
unifi_username: [REDACTED]
unifi_password: [REDACTED]

iphonedetect_thomas: [REDACTED]
iphonedetect_jessica: [REDACTED]

rest_url_kiosk_command: [REDACTED]
rest_url_kiosk_device_info: [REDACTED]
rest_url_kiosk_device_settings: [REDACTED]
