substitutions:
  name: esp32-refrigerator-temp-c932a4
  friendly_name: Temperature, Refrigerator and Freezer


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino


one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: dallas_temp
    address: 0x373ce104573b9028
    name: "Refrigerator Temperature"
    update_interval: 60s
    filters:
        - offset: -3
  - platform: dallas_temp
    address: 0x563ce1045708c728
    name: "Freezer Temperature"
    update_interval: 60s
    filters:
        - offset: -3


# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret fridge_freezer_temperature_ip_address
    gateway: !secret gateway
    subnet: !secret subnet

# Log all log messages
logger: 

# Allow web interface
captive_portal: