substitutions:
  name: esp32-bluetooth-proxy-9d2588
  friendly_name: Bluetooth Proxy, Bedroom 2
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret bluetooth_proxy_api_key_bedroom_2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
