substitutions:
  name: esp32-bluetooth-proxy-bd3784
  friendly_name: Bluetooth Proxy, Kitchen
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret bluetooth_proxy_api_key_kitchen

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
