# Your Wi-Fi SSID and password
wifi_ssid: [REDACTED]
wifi_password: [REDACTED]

gateway: [REDACTED]
subnet: [REDACTED]

# Bluetooth Proxy, Bedroom 1:
bedroom_1_btproxy_ip_address: [REDACTED]
bedroom_1_btproxy_api_key: [REDACTED]

# Bluetooth Proxy, Bedroom 2:
bedroom_2_btproxy_ip_address: [REDACTED]
bedroom_2_btproxy_api_key: [REDACTED]

# Bluetooth Proxy, Bedroom 4:
bedroom_4_btproxy_ip_address: [REDACTED]
bedroom_4_btproxy_api_key: [REDACTED]

# Bluetooth Proxy, Kitchen:
kitchen_btproxy_ip_address: [REDACTED]
kitchen_btproxy_api_key: [REDACTED]

# Fridge/Freezer
fridge_freezer_temperature_ip_address: [REDACTED]
fridge_freezer_temperature_api_key: [REDACTED]

# RATGDO
ratgdo_ip_address: [REDACTED]
ratgdo_api_key: [REDACTED]

# Upsy Desk
upsy_desk_ip_address: [REDACTED]
upsy_desk_api_key: [REDACTED]