substitutions:
  name: upsy-desky-76db20
  friendly_name: Desk, Bedroom 4

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/stock.yaml

api:
  encryption:
    key: !secret upsy_desk_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret upsy_desk_ip_address
    gateway: !secret gateway
    subnet: !secret subnet
