blueprint:
  name: GE Smart HQ Appliance
  description: Manage your GE SmartHQ enabled appliance.
  author: Thomas Maxson
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    appliance_details:
      name: Appliance Details
      icon: mdi:state-machine
      collapsed: false
      input:
        appliance_state:
          name: Appliance State
          description: >-
            The current state of the appliance.
            <br>Used to trigger actions when the appliance starts or completes its cycle."
          selector:
            entity:
              multiple: false
              filter:
                - integration: ge_home

        appliance_door:
          name: Appliance Door Sensor
          description: The current state of the appliance door.
          selector:
            entity:
              multiple: false
              filter:
                - integration: ge_home

    custom_fields:
      name: Custom Fields
      icon: mdi:dots-vertical
      collapsed: false
      input:
        appliance_complete_flag:
          name: Completed Flag
          description: >-
            Flag to set when appliance has completed its cycle.
            <br>Used to trigger repeatable actions.
          selector:
            entity:
              multiple: false
              filter:
                domain: input_boolean

    appliance_actions_start:
      name: Start Actions
      icon: mdi:contain-start
      collapsed: true
      input:
        action_single_start:
          name: Single Start Action(s)
          description: Action(s) to run once when the appliance starts.
          default: []
          selector:
            action:

    appliance_actions_finish:
      name: Finished Actions
      icon: mdi:contain-end
      collapsed: true
      input:
        action_single_finish:
          name: Single Complete Action(s)
          description: Action(s) to run once when the appliance completes its cycle.
          default: []
          selector:
            action:

        action_repeat_finish:
          name: Repeat Complete Action(s)
          description: >-
            Action(s) to repeat when the appliance completes its cycle.
            <br>These will repeat until the appliance is turned off or the door is opened.
          default: []
          selector:
            action:

        duration_repeat_finish:
          name: Repeat Duration
          description: Duration to wait until repeatable action is repeated
          default: 10
          selector:
            number:
              min: 1
              max: 60
              unit_of_measurement: minutes
              step: 1
              mode: slider

    automation_config:
      name: Configuration
      icon: mdi:cog
      collapsed: true
      input:
        config_mode:
          name: Automation Mode
          description: "Mode that the automation runs in."
          default: restart
          selector:
            select:
              options:
                - single
                - restart
                - queued
                - parallel
              custom_value: false
              multiple: false

        config_max_num:
          name: Max Number of Runs
          description: >
            Maximum number of runs that can be executed or queued at a time.
            <br>Ignored by _Single_ and _Restart_ Modes.
          default: 10
          selector:
            number:
              mode: slider
              unit_of_measurement: runs
              min: 1.0
              max: 15.0
              step: 1.0

mode: !input config_mode
max: !input config_max_num
max_exceeded: silent

triggers:
  - trigger: state
    entity_id:
      - !input appliance_state
    to: "Standby"
    id: state_to_standby

  - trigger: state
    entity_id:
      - !input appliance_state
    to: "Run"
    id: state_to_run

  - trigger: state
    entity_id:
      - !input appliance_state
    to: "On"
    id: state_to_on
  - trigger: state
    entity_id:
      - !input appliance_state
    to: "on"
    id: state_to_on

  - trigger: state
    entity_id:
      - !input appliance_state
    to: "Paused"
    id: State switched to Paused

  - trigger: state
    entity_id:
      - !input appliance_state
    to: "Finished"
    id: state_to_finished

  # - trigger: state
  #   entity_id:
  #     - !input appliance_state
  #   to: "off"
  #   id: state_to_off
  # - trigger: state
  #   entity_id:
  #     - !input appliance_state
  #   to: "Off"
  #   id: state_to_off

  - trigger: state
    entity_id:
      - !input appliance_door
    to: "on"
    id: door is_open

actions:
  - choose:
      # Appliance State is "Run"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id:
                  - state_to_run
              - condition: trigger
                id:
                  - state_to_on
              - condition: trigger
                id:
                  - State switched to on
        sequence:
          - choose: []
            default: !input action_single_start

      # Appliance State is "Finished"
      - conditions:
          - condition: trigger
            id:
              - state_to_finished
        sequence:
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input appliance_complete_flag
          - choose: []
            default: !input action_single_finish
          - repeat:
              until:
                - condition: state
                  entity_id: !input appliance_complete_flag
                  state: "off"
              sequence:
                - choose: []
                  default: !input action_repeat_finish
                - delay:
                    hours: 0
                    minutes: !input duration_repeat_finish
                    seconds: 0

      # Turn Off Complete Flag
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - door is_open
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input appliance_state
                    state: "off"
                  - condition: state
                    entity_id: !input appliance_state
                    state: "Off"
                  - condition: state
                    entity_id: !input appliance_state
                    state: "Standby"
                  - condition: state
                    entity_id: !input appliance_state
                    state: "Finished"
              - condition: state
                entity_id: !input appliance_complete_flag
                state: "on"
        sequence:
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input appliance_complete_flag
