# This blueprint uses an Aqara Mini Switch Remote Control connected through ZHA
#
# | Button | Duration     | Action        |
# | -------| ------------ | ------------- |
# | Power  | Short Press  | Custom action |
# | Power  | Double Press | Custom action |
# | Power  | Long Press   | Custom action |
# | Power  | Release      | Custom action |
# | Device | Shake        | Custom action |

blueprint:
  name: Aqara, Wireless Mini Switch
  description: Control devices with your Aqara Wireless Mini Switch.
  author: Thomas Maxson
  source_url: https://gist.github.com/thomasmaxson/67dc65d3cf0725f3d2088d38ba9f0234
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    remote:
      name: Aqara Wireless Mini Switch
      description: Aqara Mini Switch remote used to trigger actions.
      selector:
        device:
          multiple: false
          filter:
            - manufacturer: Aqara
              model: Wireless mini switch (with gyroscope) (WXKG12LM)
            - manufacturer: Aqara
              model: Wireless mini switch (with gyroscope)
            - integration: mqtt
              manufacturer: Xiaomi
              model: WXKG11LM
            - integration: zha
              manufacturer: LUMI
              model: lumi.remote.b1acn01

    remote_actions_default:
      name: Button Actions
      icon: mdi:hand-pointing-up
      collapsed: false
      input:
        single_press_action:
          name: Button Short Press
          description: The action to perform on short press of the button.
          default: []
          selector:
            action:

        double_press_action:
          name: Button Double Press
          description: The action to perform on double press of the button.
          default: []
          selector:
            action:

        long_press_action:
          name: Button Long Press
          description: The action to perform on long press of the button.
          default: []
          selector:
            action:

    remote_actions_extra:
      name: Advanced Button Actions
      icon: mdi:hand-pointing-up
      collapsed: true
      input:
        release_action:
          name: Button Release
          description: The action to perform on release of the button.
          default: []
          selector:
            action:

        release_action:
          name: Button Shake
          description: >-
            The action to perform on shake of the button.
            <br>
            <br>_Note_:
            <br>This interaction type is only available on devices with a gyroscope.
          default: []
          selector:
            action:

    automation_config:
      name: Configuration
      icon: mdi:cog
      collapsed: true
      input:
        config_mode:
          name: Automation Mode
          description: "Mode that the automation runs in."
          default: restart
          selector:
            select:
              options:
                - single
                - restart
                - queued
                - parallel
              custom_value: false
              multiple: false

        config_max_num:
          name: Max Number of Runs
          description: >
            Maximum number of runs that can be executed or queued at a time.
            <br>Ignored by _Single_ and _Restart_ Modes.
          default: 10
          selector:
            number:
              mode: slider
              unit_of_measurement: runs
              min: 1.0
              max: 15.0
              step: 1.0

    debug_config:
      name: Debug
      icon: mdi:bug
      collapsed: true
      input:
        log_valid_events:
          name: Log Valid Remote Events
          description: Display a persistent notification if a _valid event_ is triggered.
          default: false
          selector:
            boolean:

        log_invalid_events:
          name: Log Invalid Remote Events
          description: Display a persistent notification if an _invalid event_ is triggered.
          default: false
          selector:
            boolean:

mode: !input config_mode
max: !input config_max_num
max_exceeded: silent

variables:
  var_remote: !input remote
  var_debug_identifiers: "{{ device_attr( var_remote, 'identifiers' ) | list }}"
  var_debug_integration: "{{ var_debug_identifiers[0][0] | string }}"
  var_debug_trigger_data: '{{ trigger.event.data if var_debug_identifiers == "zha" else trigger }}'

triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: single
    id: single_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: single
    id: single_press

  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: double
    id: double_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: double
    id: double_press

  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: hold
    id: long_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: hold
    id: long_press

  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: release
    id: release
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: release
    id: release

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: shake
    id: shake

conditions:
  - condition: template
    value_template: "{{ var_remote | length > 0 }}"

actions:
  - if:
      - condition: template
        value_template: !input log_valid_events
    then:
      - action: persistent_notification.create
        data:
          notification_id: blueprint_debug__aqara_mini_switch__command_valid
          title: Remote Button Pressed
          message: >-
            Aqara Mini Switch remote command.
            <br>
            <br>_Device Integration_:
            <br>{{ var_debug_integration }}
            <br>
            <br>_Device ID_:
            <br>{{ var_remote }}
            <br>
            <br>_Trigger Data_:
            <br>{{ var_debug_trigger_data }}

  - choose:
      - conditions:
          - condition: trigger
            id: single_press
        sequence: !input single_press_action

      - conditions:
          - condition: trigger
            id: double_press
        sequence: !input double_press_action

      - conditions:
          - condition: trigger
            id: long_press
        sequence: !input long_press_action

      - conditions:
          - condition: trigger
            id: release
        sequence: !input release_action

      - conditions:
          - condition: trigger
            id: shake
        sequence: !input shake_action

    default:
      - condition: template
        value_template: !input log_invalid_events
      - sequence:
          - action: persistent_notification.create
            data:
              notification_id: blueprint_debug__aqara_mini_switch__command_invalid
              title: Uncaught Remote Command
              message: >-
                Aqara Mini Switch ran the default event from the "choose" event action.
                <br>Please check any automations which may not be handling this event.
                <br>
                <br>_Device Integration_:
                <br>{{ var_debug_integration }}
                <br>
                <br>_Device ID_:
                <br>{{ var_remote }}
                <br>
                <br>_Trigger Data_:
                <br>{{ var_debug_trigger_data }}
