# This blueprint uses an IKEA TRÅDFRI 5 Button Remote Control connected through ZHA
#
# | Button      | Duration    | Action              |
# | ----------- | ----------- | ------------------- |
# | Power       | Short Press | Toggle the light    |
# | Power       | Long Press  | Custom action       |
# | Dim-Up      | Short Press | Turn on             |
# | Dim-Up      | Long Press  | Increase brightness |
# | Dim-Down    | Short Press | Turn off            |
# | Dim-Down    | Long Press  | Decrease brightness |
# | Left Arrow  | Short Press | Custom action       |
# | Left Arrow  | Long Press  | Custom action       |
# | Right Arrow | Short Press | Custom action       |
# | Right Arrow | Long Press  | Custom action       |

blueprint:
  name: IKEA TRÅDFRI, 5 Button Remote Control
  description: Control devices with your IKEA TRÅDFRI 5 button remote.
  author: Thomas Maxson
  source_url: https://gist.github.com/thomasmaxson/1b776b184882ba9c85c90c20c02b423a
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    remote:
      name: IKEA TRÅDFRI remote control
      description: Select the IKEA TRÅDFRI remote to trigger your automations.
      selector:
        device:
          multiple: false
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: TRADFRI remote control

    light:
      name: Light(s)
      description: Select the light entities you wish to control.
      selector:
        entity:
          multiple: true
          filter:
            domain: light

    remote_light:
      name: Light Configuration
      icon: mdi:lightbulb-on
      collapsed: true
      input:
        brightness:
          name: Brightness
          description: >-
            Brightness of the light(s) when turning on.
            <br>Set 1-100 to use a specific brightness level
            <br>Set to 0 to use the lights last brightness level
          selector:
            number:
              mode: slider
              unit_of_measurement: "%"
              min: 0
              max: 100.0
              step: 1.0
          default: 0

        brightness_step:
          name: Brightness Step
          description: Value to increase/decrease brightness.
          selector:
            number:
              mode: slider
              unit_of_measurement: "%"
              min: 10
              max: 100
              step: 5.0
          default: 20

        repeat_duration:
          name: Repeat Duration
          description: The speed in which to update the light when the button is held.
          selector:
            number:
              mode: slider
              unit_of_measurement: milliseconds
              min: 100
              max: 1000
              step: 100
          default: 500

    additional_actions:
      name: Additional Button Actions
      icon: mdi:hand-pointing-up
      collapsed: true
      input:
        button_power_long:
          name: Power Button - Long Press
          description: The action to perform on Long Press of the Power Button
          default: []
          selector:
            action: null

    remote_actions:
      name: Left/Right Button Actions
      icon: mdi:code-tags
      collapsed: true
      input:
        button_left_short:
          name: Left Button - Short Press
          description: The action to perform on Short Press of the Left Button
          default: []
          selector:
            action: null

        button_left_long:
          name: Left Button - Long Press
          description: '
            The action to perform on Long Press of the Left Button.
            <br>Use with care, before the long press event, the "on" event gets triggered.'
          default: []
          selector:
            action: null

        button_right_short:
          name: Right Button - Short Press
          description: The action to perform on Short Press of the Right Button
          default: []
          selector:
            action: null

        button_right_long:
          name: Right Button - Long Press
          description: '
            The action to perform on Long Press of the Right Button.
            <br>Use with care, before the long press event, the "on" event gets triggered.'
          default: []
          selector:
            action: null

    automation_config:
      name: Configuration
      icon: mdi:cog
      collapsed: true
      input:
        config_mode:
          name: Automation Mode
          description: Mode that automation runs in.
          default: restart
          selector:
            select:
              options:
                - single
                - restart
                - queued
                - parallel
              custom_value: false
              multiple: false

        config_max_num:
          name: Mode Max
          description: >
            Maximum number of runs that can be executed or queued at a time.
            <br>Ignored by _Single_ and _Restart_ Modes.
          default: 10
          selector:
            number:
              mode: slider
              unit_of_measurement: runs
              min: 1.0
              max: 15.0
              step: 1.0

    debug_config:
      name: Debug
      icon: mdi:bug
      collapsed: true
      input:
        log_valid_events:
          name: Log Valid Remote Events
          description: Display a persistent notification if a _valid event_ is triggered.
          default: false
          selector:
            boolean:

        log_invalid_events:
          name: Log Invalid Remote Events
          description: Display a persistent notification if an _invalid event_ is triggered.
          default: false
          selector:
            boolean:

mode: !input config_mode
max: !input config_max_num
max_exceeded: silent

variables:
  trigger_command: "{{ trigger.event.data.command }}"
  trigger_args: "{{ trigger.event.data.args }}"
  var_light: !input light
  var_brightness: !input brightness
  var_brightness_step: !input brightness_step
  var_repeat_duration: !input repeat_duration

triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote

conditions:
  - condition: template
    value_template: "{{ var_light | length > 0 }}"

actions:
  - if:
      - condition: template
        value_template: !input log_valid_events
    then:
      - action: persistent_notification.create
        data:
          notification_id: blueprint_debug__remote_ikea_tradfri_5_button__command_valid
          title: Remote Command
          message: >-
            IKEA TRÅDFRI 5 button remote command.
            <br>
            <br>_Remote Data_: 
            <br>"{{ trigger.event.data }}"

  - choose:
      # Short-Press on the power button (ON)
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'toggle' }}"
          - condition: state
            entity_id: !input light
            state: "off"
        sequence:
          - if:
              - condition: template
                value_template: "{{ var_brightness | int > 0 }}"
            then:
              - action: light.turn_on
                target:
                  entity_id: >-
                    {{ expand( var_light ) | selectattr( 'state', 'eq', 'off' ) | map( attribute = 'entity_id' ) | list }}
                data:
                  brightness_pct: !input brightness
                  transition: "{{ ( var_repeat_duration / 1000 ) | float }}"
            else:
              - action: light.turn_on
                target:
                  entity_id: >-
                    {{ expand( var_light ) | selectattr( 'state', 'eq', 'off' ) | map( attribute = 'entity_id' ) | list }}

      # Short-Press on the power button (OFF)
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'toggle' }}"
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: >-
                {{ expand( var_light ) | selectattr( 'state', 'eq', 'on' ) | map( attribute = 'entity_id' ) | list }}

      # Long-Press on the power button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'move_to_level_with_on_off' }}"
        sequence: !input button_power_long

      # Short-Press on the dim-up button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'step_with_on_off' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: >-
                {{ expand( var_light ) | selectattr( 'state', 'eq', 'on' ) | map( attribute = 'entity_id' ) | list }}
            data:
              brightness_step_pct: "{{ var_brightness_step * 1 | int }}"
              transition: "{{ ( var_repeat_duration / 1000 ) | float }}"

      # Long-Press on the dim-up button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: >-
                      {{ expand( var_light ) | selectattr( 'state', 'eq', 'on' ) | map( attribute = 'entity_id' ) | list }}
                  data:
                    brightness_step_pct: "{{ var_brightness_step * 1 | int }}"
                    transition: "{{ ( var_repeat_duration / 1000 ) | float }}"
                - delay:
                    milliseconds: !input repeat_duration

      # Short-Press on the dim-down button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'step' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: >-
                {{ expand( var_light ) | selectattr( 'state', 'eq', 'on' ) | map( attribute = 'entity_id' ) | list }}
            data:
              brightness_step_pct: "{{ var_brightness_step * -1 | int }}"
              transition: "{{ ( var_repeat_duration / 1000 ) | float }}"

      # Long-Press on the dim-down button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'move' }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: >-
                      "{{ expand( var_light ) | selectattr( 'state', 'eq', 'on' ) | map( attribute = 'entity_id' ) | list }}"
                  data:
                    brightness_step_pct: "{{ var_brightness_step * -1 | int }}"
                    transition: "{{ ( var_repeat_duration / 1000 ) | float }}"
                - delay:
                    milliseconds: !input repeat_duration

      # Short-Press on the left button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'press' }}"
          - condition: template
            value_template: "{{ trigger_args == [257, 13, 0] }}"
        sequence: !input button_left_short

      # Long-Press on the left button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'hold' }}"
          - condition: template
            value_template: "{{ trigger_args == [3329, 0] }}"
        sequence: !input button_left_long

      # Short-Press on the right button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'press' }}"
          - condition: template
            value_template: "{{ trigger_args == [256, 13, 0] }}"
        sequence: !input button_right_short

      # Long-Press on the right button
      - conditions:
          - condition: template
            value_template: "{{ trigger_command == 'hold' }}"
          - condition: template
            value_template: "{{ trigger_args == [3328, 0] }}"
        sequence: !input button_left_long

    # Any other event will cancel the repeat loops
    # default: []

    default:
      - condition: template
        value_template: !input log_invalid_events
      - sequence:
          - action: persistent_notification.create
            data:
              notification_id: blueprint_debug__remote_ikea_tradfri_5_button__command_invalid
              title: Uncaught Remote Command
              message: >-
                IKEA TRÅDFRI 5 button remote ran the default event from the "choose" event action.
                <br>Please check any automations which may not be handling this event.
                <br>
                <br>_Remote Data_: 
                <br>"{{ trigger.event.data }}"
