# This blueprint uses an IKEA TRÅDFRI 2 Button Remote Control connected through ZHA
#
# | Button | Duration    | Action              |
# | ------ | ----------- | ------------------- |
# | On     | Short Press | Turn on             |
# | On     | Long Press  | Increase brightness |
# | Off    | Short Press | Turn off            |
# | Off    | Long Press  | Decrease brightness |

blueprint:
  name: IKEA TRÅDFRI, 2 Button Remote Control
  description: Control devices with your IKEA TRÅDFRI 2 button remote.
  author: Thomas Maxson
  source_url: https://gist.github.com/thomasmaxson/0e7f511eb9e65927708014e461a57674
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    remote:
      name: IKEA TRÅDFRI remote control
      description: Select the IKEA TRÅDFRI remote to trigger your automations.
      selector:
        device:
          multiple: false
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: TRADFRI on/off switch

    light:
      name: Light(s)
      description: Select the light entities you wish to control.
      selector:
        entity:
          multiple: true
          filter:
            domain: light

    light_config:
      name: Light Configuration
      icon: mdi:lightbulb-on
      collapsed: false
      input:
        brightness:
          name: Brightness
          description: >-
            Brightness of the light(s) when turning on.
            <br>Set 1-100 to use a specific brightness level
            <br>Set to 0 to use the lights last brightness level
          selector:
            number:
              mode: slider
              unit_of_measurement: "%"
              min: 0
              max: 100.0
              step: 1.0
          default: 0

        brightness_step:
          name: Brightness Step
          description: Value to increase/decrease brightness.
          selector:
            number:
              mode: slider
              unit_of_measurement: "%"
              min: 10
              max: 100
              step: 5.0
          default: 20

        repeat_duration:
          name: Repeat Duration
          description: The speed in which to update the light when the button is held.
          selector:
            number:
              mode: slider
              unit_of_measurement: milliseconds
              min: 100
              max: 1000
              step: 100
          default: 500

    automation_config:
      name: Configuration
      icon: mdi:cog
      collapsed: true
      input:
        config_mode:
          name: Automation Mode
          description: Mode that automation runs in.
          default: restart
          selector:
            select:
              options:
                - single
                - restart
                - queued
                - parallel
              custom_value: false
              multiple: false

        config_max_num:
          name: Mode Max
          description: >
            Maximum number of runs that can be executed or queued at a time.
            <br>Ignored by _Single_ and _Restart_ Modes.
          default: 10
          selector:
            number:
              mode: slider
              unit_of_measurement: runs
              min: 1.0
              max: 15.0
              step: 1.0

    debug_config:
      name: Debug
      icon: mdi:bug
      collapsed: true
      input:
        log_valid_events:
          name: Log Valid Remote Events
          description: Display a persistent notification if a _valid event_ is triggered.
          default: false
          selector:
            boolean:

        log_invalid_events:
          name: Log Invalid Remote Events
          description: Display a persistent notification if an _invalid event_ is triggered.
          default: false
          selector:
            boolean:

mode: !input config_mode
max: !input config_max_num
max_exceeded: silent

variables:
  var_light: !input light
  var_repeat: !input repeat_duration
  var_brightness: !input brightness
  var_brightness_step: !input brightness_step

triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote

conditions:
  - condition: template
    value_template: "{{ var_light | length > 0 }}"

actions:
  - if:
      - condition: template
        value_template: !input log_valid_events
    then:
      - action: persistent_notification.create
        data:
          notification_id: blueprint_debug__remote_ikea_tradfri_2_button__command_valid
          title: Remote Command
          message: >-
            IKEA TRÅDFRI 2 button remote command.
            <br>
            <br>_Remote Data_: 
            <br>"{{ trigger.event.data }}"

  - choose:
      # Short-Press on the on button
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on' }}"
          - condition: state
            entity_id: !input light
            state: "off"
        sequence:
          sequence:
            - if:
                - condition: template
                  value_template: "{{ var_brightness | int > 0 }}"
              then:
                - action: light.turn_on
                  target:
                    entity_id: >-
                      {{ expand( var_light ) | selectattr( 'state', 'eq', 'off' ) | map( attribute = 'entity_id' ) | list }}
                  data:
                    brightness_pct: !input brightness
                    transition: "{{ ( var_repeat / 1000 ) | float }}"
              else:
                - action: light.turn_on
                  target:
                    entity_id: !input light

      # Short-Press on the off button
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off' }}"
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: >-
                {{ expand( var_light ) | selectattr( 'state', 'eq', 'on' ) | map( attribute = 'entity_id' ) | list }}

      # Long-Press on the on button
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: >-
                      {{ expand( var_light ) | selectattr( 'state', 'eq', 'off' ) | map( attribute = 'entity_id' ) | list }}
                  data:
                    brightness_step_pct: "{{ var_brightness_step * 1 | int }}"
                    transition: "{{ ( var_repeat / 1000 ) | float }}"
                - delay:
                    milliseconds: !input repeat_duration

      # Long-Press on the off button
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: >-
                      {{ expand( var_light ) | selectattr( 'state', 'eq', 'off' ) | map( attribute = 'entity_id' ) | list }}
                  data:
                    brightness_step_pct: "{{ var_brightness_step * -1 | int }}"
                    transition: "{{ ( var_repeat / 1000 ) | float }}"
                - delay:
                    milliseconds: !input repeat_duration

    # Any other event will cancel the repeat loops
    # default: []

    default:
      - condition: template
        value_template: !input log_invalid_events
      - sequence:
          - action: persistent_notification.create
            data:
              notification_id: blueprint_debug__remote_ikea_tradfri_2_button__command_invalid
              title: Uncaught Remote Command
              message: >-
                IKEA TRÅDFRI 2 button remote ran the default event from the "choose" event action.
                <br>Please check any automations which may not be handling this event.
                <br>
                <br>_Remote Data_: 
                <br>"{{ trigger.event.data }}"
