blueprint:
  name: Manage Area State via Sensors
  description: >-
    Manage occupancy state via multiple sensors.

    - Control what happens when a door opens or occupancy is detected.
    - Control what happens when a door closes or occupancy is cleared.
  author: Thomas Maxson
  source_url: https://gist.github.com/thomasmaxson/635084f3a7f8e1877542c210b39c6ed5
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    sensor_door:
      name: Door Sensor
      selector:
        entity:
          multiple: false
          filter:
            domain: binary_sensor

    sensor_occupancy:
      name: Occupancy Sensor
      selector:
        entity:
          multiple: false
          filter:
            domain: binary_sensor


    group_door_specific_actions:
      name: Door Actions
      icon: mdi:door
      collapsed: true
      input:
        enable_door_action:
          name: Door Opened Action(s)
          description: Action(s) to perform when the door is opened.
          default: []
          selector:
            action:

        disable_door_action:
          name: Door Closed Action(s)
          description: Action(s) to perform when the door is closed.
          default: []
          selector:
            action:


    group_occupancy_specific_actions:
      name: Occupancy Actions
      icon: mdi:account
      collapsed: true
      input:
        action_occupancy_detect_instant:
          name: Occupancy Detected Action(s)
          description: Action(s) to perform when occupancy is detected.
          default: []
          selector:
            action:

        delay_occupancy_detect_instant:
          name: Occupancy Detected Delay
          description: The amount of time to wait until occupancy detected actions are triggered.
          default: 0
          selector:
            number:
              mode: box
              unit_of_measurement: seconds
              min: 0.0
              max: 3600.0
              step: 1.0

        action_occupancy_clear_instant:
          name: Occupancy Cleared Action(s)
          description: Action(s) to perform when occupancy is cleared.
          default: []
          selector:
            action:

        delay_occupancy_clear_instant:
          name: Occupancy Cleared Delay
          description: The amount of time to wait until occupancy cleared actions are triggered.
          default: 0
          selector:
            number:
              mode: box
              unit_of_measurement: seconds
              min: 0.0
              max: 3600.0
              step: 1.0


variables:
  var_enable_door_action: !input enable_door_action
  var_disable_door_action: !input disable_door_action

  var_action_occupancy_detect_instant: !input action_occupancy_detect_instant
  var_delay_occupancy_detect_instant: !input delay_occupancy_detect_instant

  var_action_occupancy_clear_instant: !input action_occupancy_clear_instant
  var_delay_occupancy_clear_instant: !input delay_occupancy_clear_instant


triggers:
  - alias: "When door is OPENED"
    trigger: state
    entity_id: !input sensor_door
    from: "off"
    to: "on"
    id: trigger_door_open

  - alias: "When door is CLOSED"
    trigger: state
    entity_id: !input sensor_door
    from: "on"
    to: "off"
    id: trigger_door_close

  - alias: "When motion is DETECTED"
    trigger: state
    entity_id: !input sensor_occupancy
    from: "off"
    to: "on"
    for: 
      hours: 0
      minutes: 0
      seconds: !input delay_occupancy_detect_instant
    id: trigger_motion_detect

  - alias: "When motion is CLEARED"
    trigger: state
    entity_id: !input sensor_occupancy
    from: "on"
    to: "off"
    for: 
      hours: 0
      minutes: 0
      seconds: !input delay_occupancy_clear_instant
    id: trigger_motion_clear


actions:
  - alias: "Choose actions to check and run"
    choose:
      - alias: "Actions to perform if DOOR OPENED"
        conditions:
          - condition: and
            conditions:
              - alias: "Check if trigged by event"
                condition: trigger
                id: trigger_door_open
              - condition: template
                value_template: "{{ var_enable_door_action is defined }}"
        sequence: !input enable_door_action


      - alias: "Actions to perform if DOOR CLOSED"
        conditions:
          - condition: and
            conditions:
              - alias: "Check if trigged by event"
                condition: trigger
                id: trigger_door_close
              - alias: "Check if custom action is defined"
                condition: template
                value_template: "{{ var_disable_door_action is defined }}"
        sequence: !input disable_door_action


      - alias: "Actions to perform when MOTION DETECTED"
        conditions:
          - condition: and
            conditions:
              - alias: "Check if trigged by event"
                condition: trigger
                id: trigger_motion_detect
              - condition: template
                value_template: "{{ trigger.from_state.state == 'off' }}"
              - condition: template
                value_template: "{{ trigger.to_state.state == 'on' }}"
              - alias: "Check if custom action is defined"
                condition: template
                value_template: "{{ var_action_occupancy_detect_instant is defined }}"
        sequence: !input action_occupancy_detect_instant


      - alias: "Actions to perform when MOTION CLEARED"
        conditions:
          - condition: and
            conditions:
              - alias: "Check if trigged by event"
                condition: trigger
                id: trigger_motion_clear
              - condition: template
                value_template: "{{ trigger.from_state.state == 'on' }}"
              - condition: template
                value_template: "{{ trigger.to_state.state == 'off' }}"
              - alias: "Check if custom action is defined"
                condition: template
                value_template: "{{ var_action_occupancy_clear_instant is defined }}"
        sequence: !input action_occupancy_clear_instant


mode: restart
max_exceeded: silent
